version: '3.9'

services:
  fluentd:
    build: ./fluentd
    container_name: fluentd
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      - efk-net
    volumes:
      - $PWD/fluentd/fluent.conf:/fluentd/etc/fluent.conf

  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elastic
    expose:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - $PWD/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    networks:
      - efk-net

  kibana:
    image: kibana:8.8.0
    container_name: kibana
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - TZ=Europe/Amsterdam
      # - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
    volumes:
      - $PWD/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - efk-net

  web:
    image: httpd
    container_name: httpd
    ports:
      - "8010:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        #fluentd-async-connect: "true"
        tag: httpd.access

volumes:
  esdata:
    name: esdata

networks:
  efk-net:
    name: efk-net